services:
  ufa-pg-db:
    image: postgres:16-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
